#!/usr/bin/python

import requests
import sys
from subprocess import Popen
from auth import *

message = "TONES RECEIVED. Stand by for text message dispatch."
data = {"verification":verification,"dispatch":message}
r = requests.post(url = url, data = data)

Popen([sys.executable, '/home/pi/tl/emergency.py'])
