#!/usr/bin/python

import requests
import sys
from subprocess import Popen
from auth import *
from datetime import *

d = datetime.now()

message = "TONES RECEIVED. Stand by for text message dispatch."

if (d.weekday() == 0 and d.hour == 18 and d.minute >= 0 and d.minute <= 10):
    message = "TONES RECEIVED but likely to be the weekly pager test. Confirm a possible call using other means."

data = {"verification":verification,"dispatch":message}
r = requests.post(url = url, data = data)

Popen([sys.executable, '/home/pi/tl/emergency.py'])
